"""Build index.html from the artifact source.

tombola-ninety.html is authored as artifact *content*: no doctype, <html>,
<head> or <body> of its own, because the Claude Artifact platform supplies
those at publish time. This wraps it in an equivalent skeleton so the same
page can be served as an ordinary static site (GitHub Pages, or any local
web server).

    python build.py

Edit tombola-ninety.html, never index.html - index.html is generated and any
hand edits to it are lost on the next build.
"""

import io
import os

# The source opens with <title>/<link>/<style> and then its first <div>, so it
# is spliced in while the parser is still in head: the div implicitly closes
# head and opens body, exactly as it does on the Artifact platform.
HEAD = """<!doctype html>
<html lang="en">
<head>
<!-- Generated by build.py from tombola-ninety.html - do not edit by hand. -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="A 90-ball bingo blower: balls churn in the drum, one drops down the glass chute showing only its colour, then fills the screen with its number.">
<meta name="theme-color" content="#070A0F">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='15' fill='%23FFCE21'/%3E%3Ccircle cx='11' cy='11' r='4.5' fill='%23ffffff' opacity='.55'/%3E%3C/svg%3E">
<style>
:root{color-scheme:dark;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}
body{margin:0;font:14px system-ui,sans-serif;background:#070A0F}
img{max-width:100%}
[hidden]{display:none!important}
</style>
"""

TAIL = """
</body>
</html>
"""

here = os.path.dirname(os.path.abspath(__file__))
src = io.open(os.path.join(here, "tombola-ninety.html"), encoding="utf-8").read()

out = os.path.join(here, "index.html")
io.open(out, "w", encoding="utf-8", newline="\n").write(HEAD + src + TAIL)
print("wrote %s (%d bytes)" % (out, os.path.getsize(out)))
